### ISSUE TITLE
Update ReadMe Documentation

### ISSUE THREAD

**Issue by curtisma** [cascode-labs/build-conda-action#3]
**Problem Statement**
----------------------------

The ReadMe should highlight that this action is simple to use, but still flexible.

**Proposed Solution**
-------------------------------------------

Update the ReadMe to highlight the usage.

- [x] Create a new "Usage section right after the overview
  - [x] Highlight that inputs are not required for the basic config but can be used to customize the build config.
  - [x] Document the basic conda config required to run the action
  - [x] Add an example of simple usage in a workflow
- [x] Add notes and an example workflow showing how to use a custom yml conda build env description file.

**Alternatives Considered**
-----------------------------------------------

**Proposed Action Plan**
-------------------------------
- [x] 1. Update the ReadMe using the guidelines described in the solution.
- [x] 2. Add a test case which uses a custom build.yml env definition file.

**Comment by JadenC1126** [comment]
![image](https://user-images.githubusercontent.com/65977732/131553149-5446cf32-2298-4239-8445-9ebca6db402c.png)

this is what i have so far for the readme, wasn't sure how to call the specific action --> working on finding that now 

@curtisma

**Comment by curtisma** [comment]
Ok, go ahead and commit what you have.  I'll go in and edit it.
